Description: >
  This template create a KMS Key

Resources:
  KMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: KMS key for studing
      EnableKeyRotation: true
      PendingWindowInDays: 20
      KeyPolicy:
        Version: '2012-10-17'
        Id: key-default-1
        Statement:
        - Sid: Allow administration of the key
          Effect: Allow
          Principal:
            AWS: arn:aws:iam::268919435141:user/le.bevilaqua
          Action:
          - kms:Create*
          - kms:Describe*
          - kms:Enable*
          - kms:List*
          - kms:Put*
          - kms:Update*
          - kms:Revoke*
          - kms:Disable*
          - kms:Get*
          - kms:Delete*
          - kms:ScheduleKeyDeletion
          - kms:CancelKeyDeletion
          Resource: '*'
        - Sid: Allow use of the key
          Effect: Allow
          Principal:
            AWS: arn:aws:iam::268919435141:user/le.bevilaqua
          Action:
          - kms:DescribeKey
          - kms:Encrypt
          - kms:Decrypt
          - kms:ReEncrypt*
          - kms:GenerateDataKey
          - kms:GenerateDataKeyWithoutPlaintext
          Resource: '*'

Outputs:
  KMSKey:
    Description: A reference to the KMS Key
    Value: !Ref KMSKey
  KMSKeyArn:
    Description: A reference to the KMS Key ARN
    Value: !GetAtt 'KMSKey.Arn'